### PR TITLE
Update pins_RAMBO.h

### PR DESCRIPTION
**Pull request by adolson**
ifndef for several pins to support Thinker SE pins

### CODE REVIEW

**Comment by bryanpedini** [comment]
Thanks (even tho you could either make a single commit for both files, or send two commits under the same pull request 😉).

**Comment by adolson** [comment]
Haha, yeah, I just edited the files directly on Github with my changes, since they weren't too much, and am not overly familiar with working with other people's forks/branches/pull requests and such. Wasn't real sure how to do it without pulling a whole other copy of the repo, and I have a monthly data cap of 50GB right now (waiting for a Starlink beta invite), so I try to pull down as little as I can. :(

**Comment by bryanpedini** [comment]
No worry, just pointed out joking and for future reference, no offence whatsoever!
Have a nice day and thanks again for the contribution (did you need the Z endstop pin changed? I didn't 🧐).

**Comment by adolson** [comment]
I just ran M43 on Eryone's Marlin and my own vanilla Marlin and saw that Z_MIN_PIN was not being set correctly, and that's when I realized it was being overridden in this file. Before my change, when I tried to home with BLTouch, XY and would go fine, but the probe would deploy and stow a few times, and Z wouldn't budge... After my fix, it homes correctly.

Here's a full dump of their M115 and M43, if your're curious.

> Send: N1 M115*39
Recv: FIRMWARE_NAME:Marlin 2.0.x (GitHub) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Thinker V2_BL_FL EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:0
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:0
Recv: Cap:PROMPT_SUPPORT:0
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:CHAMBER_TEMPERATURE:0




> Recv: PIN:   0   Port: E0        RXD                                    protected
Recv: PIN:   1   Port: E1        TXD                                    protected
Recv: PIN:   2   Port: E4        FAN1_PIN                               protected
Recv: PIN:   3   Port: E5        HEATER_BED_PIN                         protected
Recv: PIN:   4   Port: G5        SERVO0_PIN                             Output = 0    TIMER0B   PWM:   128    WGM: 3    COM0\x83: 3    CS: 3    TCCR0A: 3    TCCR0B: 3    TIMSK0: 5   compare interrupt enabled   overflow interrupt enabled
Recv: PIN:   5   Port: E3        SERVO3_PIN                             Input  = 0    TIMER3A   PWM:  -25536    WGM: 0    COM3\x82: 0    CS: 2    TCCR3A: 0    TCCR3B: 2    TIMSK3: 2   non-standard PWM mode   compare interrupt enabled
Recv: PIN:   6   Port: H3        E0_AUTO_FAN_PIN                        protected
Recv: .                          FAN2_PIN                               protected
Recv: .                          HEATER_2_PIN                           protected
Recv: PIN:   7   Port: H4        HEATER_1_PIN                           Output = 0    TIMER4B   PWM:     0    WGM: 1    COM4\x83: 1    CS: 3    TCCR4A: 1    TCCR4B: 3    TIMSK4: 0
Recv: PIN:   8   Port: H5        FAN_PIN                                protected
Recv: PIN:   9   Port: H6        HEATER_0_PIN                           protected
Recv: PIN:  10   Port: B4        FIL_RUNOUT_PIN                         Input  = 1    TIMER2A   PWM:     0    WGM: 1    COM2\x82: 1    CS: 4    TCCR2A: 1    TCCR2B: 4    TIMSK2: 0
Recv: PIN:  11   Port: B5        Y_MIN_PIN                              protected
Recv: .                          Y_STOP_PIN                             protected
Recv: PIN:  12   Port: B6        X_MIN_PIN                              protected
Recv: .                          X_STOP_PIN                             protected
Recv: PIN:  13   Port: B7        LED_PIN                                Input  = 0    TIMER0A   PWM:     0    WGM: 3    COM0\x82: 3    CS: 3    TCCR0A: 3    TCCR0B: 3    TIMSK0: 5   overflow interrupt enabled
Recv:  .                  TIMER1C is also tied to this pin                  TIMER1C   PWM:     0    WGM: 4    COM1\x84: 0    CS: 2    TCCR1A: 0    TCCR1B: 10    TIMSK1: 2   non-standard PWM mode
Recv: PIN:  14   Port: J1        <unused/unknown>                       Input  = 0
Recv: PIN:  15   Port: J0        <unused/unknown>                       Input  = 0
Recv: PIN:  16   Port: H1        E_MUX1_PIN                             Input  = 0
Recv: PIN:  17   Port: H0        E_MUX0_PIN                             Input  = 0
Recv: PIN:  18   Port: D3        <unused/unknown>                       Input  = 0
Recv: PIN:  19   Port: D2        <unused/unknown>                       Input  = 0
Recv: PIN:  20   Port: D1        <unused/unknown>                       Input  = 0
Recv: PIN:  21   Port: D0        <unused/unknown>                       Input  = 0
Recv: PIN:  22   Port: A0        COOLANT_MIST_PIN                       protected
Recv: .                          Z_MIN_PIN                              protected
Recv: .                          Z_STOP_PIN                             protected
Recv: PIN:  23   Port: A1        SERVO1_PIN                             Input  = 0
Recv: PIN:  24   Port: A2        <unused/unknown>                       Input  = 0
Recv: PIN:  25   Port: A3        E1_ENABLE_PIN                          protected
Recv: .                          Z2_ENABLE_PIN                          protected
Recv: PIN:  26   Port: A4        E0_ENABLE_PIN                          protected
Recv: PIN:  27   Port: A5        Z_ENABLE_PIN                           protected
Recv: PIN:  28   Port: A6        Y_ENABLE_PIN                           protected
Recv: PIN:  29   Port: A7        X_ENABLE_PIN                           protected
Recv: PIN:  30   Port: C7        <unused/unknown>                       Input  = 0
Recv: PIN:  31   Port: C6        <unused/unknown>                       Input  = 0
Recv: PIN:  32   Port: C5        <unused/unknown>                       Input  = 0
Recv: PIN:  33   Port: C4        E1_STEP_PIN                            protected
Recv: .                          Z2_STEP_PIN                            protected
Recv: PIN:  34   Port: C3        E0_STEP_PIN                            protected
Recv: PIN:  35   Port: C2        Z_STEP_PIN                             protected
Recv: PIN:  36   Port: C1        Y_STEP_PIN                             protected
Recv: PIN:  37   Port: C0        X_STEP_PIN                             protected
Recv: PIN:  38   Port: D7        DIGIPOTSS_PIN                          Output = 1
Recv: PIN:  39   Port: G2        Y_MS2_PIN                              protected
Recv: PIN:  40   Port: G1        X_MS1_PIN                              protected
Recv: PIN:  41   Port: G0        X_MS2_PIN                              protected
Recv: PIN:  42   Port: L7        E1_DIR_PIN                             protected
Recv: .                          Z2_DIR_PIN                             protected
Recv: PIN:  43   Port: L6        E0_DIR_PIN                             protected
Recv: PIN:  44   Port: L5        COOLANT_FLOOD_PIN                      Input  = 1    TIMER5C   PWM:     0    WGM: 1    COM5\x84: 0    CS: 3    TCCR5A: 1    TCCR5B: 3    TIMSK5: 0
Recv: PIN:  45   Port: L4        <unused/unknown>                       Input  = 0                           TIMER5B   PWM:     0    WGM: 1    COM5\x83: 1    CS: 3    TCCR5A: 1    TCCR5B: 3    TIMSK5: 0
Recv: PIN:  46   Port: L3        CASE_LIGHT_PIN                         Input  = 0    TIMER5A   PWM:     0    WGM: 1    COM5\x82: 1    CS: 3    TCCR5A: 1    TCCR5B: 3    TIMSK5: 0
Recv: PIN:  47   Port: L2        Z_DIR_PIN                              protected
Recv: PIN:  48   Port: L1        X_DIR_PIN                              protected
Recv: PIN:  49   Port: L0        Y_DIR_PIN                              protected
Recv: PIN:  50   Port: B3        AVR_MISO_PIN                           Input  = 0
Recv: .                          MISO_PIN                               Input  = 0
Recv: PIN:  51   Port: B2        AVR_MOSI_PIN                           Output = 1
Recv: .                          DOGLCD_MOSI                            Output = 1
Recv: .                          MOSI_PIN                               Output = 1
Recv: PIN:  52   Port: B1        AVR_SCK_PIN                            Output = 0
Recv: .                          DOGLCD_SCK                             Output = 0
Recv: .                          SCK_PIN                                Output = 0
Recv: PIN:  53   Port: B0        AVR_SS_PIN                             Output = 1
Recv: .                          SDSS                                   Output = 1
Recv: .                          SS_PIN                                 Output = 1
Recv: PIN:  54   Port: F0 (A 0)  TEMP_0_PIN                             protected
Recv: PIN:  55   Port: F1 (A 1)  TEMP_1_PIN                             Analog in =  1023
Recv: PIN:  56   Port: F2 (A 2)  TEMP_BED_PIN                           protected
Recv: PIN:  57   Port: F3 (A 3)  FILWIDTH_PIN                           Analog in =   799
Recv: PIN:  58   Port: F4 (A 4)  <unused/unknown>   Analog in =   818   Input  = 1
Recv: PIN:  59   Port: F5 (A 5)  <unused/unknown>   Analog in =   697   Input  = 1
Recv: PIN:  60   Port: F6 (A 6)  <unused/unknown>   Analog in =   806   Input  = 1
Recv: PIN:  61   Port: F7 (A 7)  <unused/unknown>   Analog in =   680   Input  = 1
Recv: PIN:  62   Port: K0 (A 8)  <unused/unknown>   Analog in =   814   Input  = 1
Recv: PIN:  63   Port: K1 (A 9)  BTN_EN2                                protected
Recv: .                          E1_MS1_PIN                             protected
Recv: .                          Z2_MS1_PIN                             protected
Recv: PIN:  64   Port: K2 (A10)  BTN_EN1                                protected
Recv: .                          E1_MS2_PIN                             protected
Recv: .                          Z2_MS2_PIN                             protected
Recv: PIN:  65   Port: K3 (A11)  E0_MS1_PIN                             protected
Recv: PIN:  66   Port: K4 (A12)  E0_MS2_PIN                             protected
Recv: PIN:  67   Port: K5 (A13)  Z_MS2_PIN                              protected
Recv: PIN:  68   Port: K6 (A14)  Z_MS1_PIN                              protected
Recv: PIN:  69   Port: K7 (A15)  Y_MS1_PIN                              protected
Recv: ok

**Comment by bryanpedini** [comment]
Stupid BL-Touch didn't work on my board 'cause they not only swapped two wires on the daughter board near the extruder, but also the wiring between the board connectors and the processor too (PINs)??

**Comment by adolson** [comment]
Yeah, I really, really don't understand why that is... But I knew that before buying my BLTouch, so I just swapped the pins in the Dupont connector per their diagram and it works... Really shouldn't HAVE to, though.

**Comment by bryanpedini** [comment]
> Yeah, I really, really don't understand why that is...

Well, simple: like here in IT when something bad happens at Parliament or Government, answer is "heh, Italy, only Italy", same goes for "meh, Eryone..." 😂

> But I knew that before buying my BLTouch

Good for you! (I fried a sensor in the meanwhile)

**Pull request merged**
